name: NeuraFund CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # JOB 1: TEST BACKEND
  backend-test:
    # FIX: We pin this to 'ubuntu-22.04' because the DB tool fails on the newer ubuntu-latest
    runs-on: ubuntu-22.04
    
    defaults:
      run:
        working-directory: ./Backend

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Install Dependencies
      # We stick with the standard install now that we fixed the OS version
      run: |
        npm install
        npm install --save-dev cross-env
        npm install --save-dev mongodb-memory-server
    
    - name: Run Backend Tests
      # We keep the timeout increase just to be safe
      run: npx jest --testTimeout=60000 --detectOpenHandles --forceExit
      env:
        INTASEND_PUBLISHABLE_KEY: test_pub_key
        INTASEND_SECRET_KEY: test_secret_key
        INTASEND_IS_TEST: true
        JWT_SECRET: test_jwt_secret

  # JOB 2: TEST FRONTEND
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run Frontend Unit Tests
      run: npm test
      env:
        CI: true


  # JOB 3: DEPLOY BACKEND (CD)
  # deploy-backend:
  #   needs: [backend-test, frontend-test]
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger Render Deployment
  #       run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"